Attribute VB_Name = "Error_Utils"
Option Explicit

Enum ErrorMsgType
    BAD_ARGUMENT = 555
    DEPENDENT_ATTR_NOT_SET = 556
    BAD_FILE_EXTENSION = 557
    NULL_OBJECT = 558
    BAD_ENUM = 559
    NOT_SINGLE_WIDGET_RANGE = 600
    NAMED_RANGE_NOT_EXIST = 601
    FORMAT_NOT_DEFINED = 602
    INVALID_WIDGETTYPE = 603
    INVALID_FORMTYPE = 604
    CACHE_TABLE_NAME_CANNOT_BE_BLANK = 605
    FIELD_NAME_CANNOT_BE_BLANK = 605
    
    ' Definitions
    INVALID_DEFN_TYPE = 700
    
End Enum
