Attribute VB_Name = "Error_Utils"
Option Explicit

Enum ErrorMsgType
    BAD_ARGUMENT = 555
    DEPENDENT_ATTR_NOT_SET = 556
    BAD_FILE_EXTENSION = 557
    NULL_OBJECT = 558
    BAD_ENUM = 559
    NOT_SINGLE_CELL_RANGE = 600
    NAMED_RANGE_NOT_EXIST = 601
    FORMAT_NOT_DEFINED = 602
End Enum
